/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */
#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#ifndef INTERFACE_H
#define INTERFACE_H

#include "support.h"
#include "misc.h"
void check_up_theme( GtkWidget *window1, APP_data *data_app );
void get_theme_selection_color(GtkWidget *widget);
void set_up_view( GtkWidget *window1, APP_data *data );
GtkWidget *create_aboutPlanlibre (APP_data *data_app);
void planlibre_prepare_GUI (GApplication *app, APP_data *data);
#endif /* INTERFACE_H */
