/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */
#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif


#ifndef SAVESTATE_H
#define SAVESTATE_H


#include "support.h"
#include "misc.h"



/* structures */


/* functions */

gint storage_save( gchar *pathname, APP_data *data_app);
void createGKeyFile(APP_data *data_app, GtkWidget *win);
void destroyGKeyFile(APP_data *data_app, GtkWidget *win);
void storeGKeyFile(APP_data *data_app, GKeyFile *keyString);
void store_current_file_in_keyfile(GKeyFile *keyString, gchar *filename, gchar *summary);
void rearrange_recent_file_list(GKeyFile *keyString);

#endif /* SAVESTATE_H */
