/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */
#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif


#ifndef SETTINGS_H
#define SETTINGS_H

#include <stdlib.h>
#include <gtk/gtk.h>
#include "support.h"
#include "misc.h"

/* functions */
void settings (APP_data *data);
gint settings_dialog_password (APP_data *data);
const gchar *settings_get_password (void);

#endif /* SETTINGS_H */

